---
title: "Publications"
editor: visual
---

::: callout-note
## Links

> -   **Google Scholar**: <https://scholar.google.com/citations?user=VN17GCMAAAAJ&hl>
> -   **ORCID**: <https://orcid.org/0000-0001-5426-590X>
:::

## Peer-reviewed

\[11\] **Li J.** 2025. *(interview)* Scientific mobility in microbiology - 8. [*Trends in microbiology*]{.underline}, S0966-842X(25)00252-5. https://doi.org/10.1016/j.tim.2025.08.009.

\[10\] **Li, J,** King, K. 2025. *(Perspective)* Microbial Primer: Microbiome and thermal tolerance - a new frontier in climate resilience?. [*Microbiology*,]{.underline} 171(1), 001523.https://doi.org/10.1099/mic.0.001523.  – Media: \[Microbial Talk Podcast\]

\[9\] **Li, J,** Smith, C. A., Chen, J., Bates, K.A., King, K. C. 2025. Warming during different life stages has distinct impacts on host resistance ecology and evolution. [*Ecology letters*]{.underline}*.* 10.1111/ele.70087. 

\[8\]  Stevens, E, **Li, J,** Hector, T, Drew, G, K. Hoang, Greenrod, S, Paterson S, King K. C. 2025. Within-host competition sparks pathogen molecular evolution and perpetual microbiota dysbiosis. [*The ISME journal*]{.underline}. https://doi.org/10.1093/ismejo/wraf071.

\[7\] **Li, J,** N. Guttmann, G. C. Drew, J. Wolinska, K. C. King. 2024. Excess mortality of infected ectotherms induced by climate change depends on pathogen kingdom and evolutionary history. [*PLoS biology*]{.underline} 22(11): e3002900. https://doi.org/10.1371/journal.pbio.3002900. -- Media: \[Fairchild TV\] \[University of British Columbia News\]

\[6\]  Gao, Y, Kai P, et al., **Li, J,** et al. 2024. “The Microbiome Protocols eBook Initiative: Building a Bridge to Microbiome Research.” [*iMeta*]{.underline} 3, e182. https://doi.org/10.1002/imt2.182.

\[5\] **Li, J**, Y. Gao, Stevens. E, King. K. C. 2024. Dual stressors of infection and warming can destabilize host microbiomes. [*Philosophical transactions of the Royal Society of London*. *Series B, Biological sciences*]{.underline}*.* 10.1098/rstb.2023.0069.

\[4\]  Hanski, E, Khanyari, M, **Li, J,** Bates, K. A, Zuther, S, Maiden, M. C. J, Kock, R, & Knowles, S. C. L. 2023. Gut microbiota of the critically endangered Saiga antelope across two wild populations in a year without mass mortality. [*Scientific reports*]{.underline}, 13(1), 17236.

\[3\] **Li, J,** Bates, K, Hoang, K, Hector, T, Knowles, S, & King, K. C. 2023. Experimental temperatures shape host microbiome diversity and composition. [*Global change biology*.]{.underline} 10.1111/gcb.16429.

\[2\]  Hector, T. E, Hoang, K. L, **Li, J,** King, K. C. 2022. *(review)* Symbiosis and host responses to heat. [*Trends in ecology & evolution*]{.underline} 37, 611-624.

\[1\]  Hui-Meng Lu\*, **Li, J\*,** Yu-Dan Zhang, Xiao-Li Lu, Chang Xu, Yuan Huang, Michael Gribskov. 2020. The evolution history of Fe-S cluster A-type assembly protein reveals multiple gene duplication events and essential protein motifs. [*Genome biology and evolution*]{.underline}12(3):160-173.
